%% Setup
project_root = fileparts(mfilename('fullpath'));
addpath(genpath(fullfile(project_root, 'Core')));

geometry_config = load(fullfile(project_root, 'geometry_config.mat'), ...
    'rocket_default_values');
rocket_prebaked = geometry_config.rocket_default_values;

%% Models
rocket_prebaked.models = { ...
    @mjollnir_mass_mapping, ...
    @base_manual_atmosphere_model, ...
    @base_drag_coefficient_model, ...
    @base_aerodynamics_model, ...
    @mjollnir_propulsion_model, ...
    @base_gravity_model, ...
    @base_dual_deploy_parachute_model, ...
    @base_equations_of_motion_model, ...
    @base_ground_interaction_model, ...
    @mjollnir_mass_model ...
};
rocket_initial_values = bake_rocket(rocket_prebaked, true);

%% Settings.
rocket_initial_values.ode_solver = @ode45;
rocket_initial_values.t_max = 20;

%% Simulation
rocket_results = simulate_rocket(rocket_initial_values);
results_path = fullfile(project_root, 'initial_values_config_simulated.mat');
save(results_path, 'rocket_initial_values', 'rocket_results', '-v7.3');
